# Generated by Django 4.2.5 on 2023-11-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('switch', 'Switch'), ('access_point', 'Access Point')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
